# This is a generated file. Not intended for manual editing.
services:
  apigateway:
    build:
      context: "/Users/Kì 9/DeloymentPAYmentAPI/SEP490_Ezstay"
      dockerfile: "ApiGateway/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/APIGateway.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "apigateway:dev"
    ports: []
    volumes:
    - "/Users/quochien/.nuget/packages:/root/.nuget/packages"
    - "/Users/Kì 9/DeloymentPAYmentAPI/SEP490_Ezstay/APIGateway:/app:rw"
    - "/Users/Kì 9/DeloymentPAYmentAPI/SEP490_Ezstay:/src:rw"
    working_dir: "/app"
  authapi:
    build:
      context: "/Users/Kì 9/DeloymentPAYmentAPI/SEP490_Ezstay"
      dockerfile: "AuthApi/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/AuthApi.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "authapi:dev"
    ports: []
    volumes:
    - "/Users/quochien/.nuget/packages:/root/.nuget/packages"
    - "/Users/Kì 9/DeloymentPAYmentAPI/SEP490_Ezstay/AuthApi:/app:rw"
    - "/Users/Kì 9/DeloymentPAYmentAPI/SEP490_Ezstay:/src:rw"
    working_dir: "/app"
  paymentapi:
    build:
      context: "/Users/Kì 9/DeloymentPAYmentAPI/SEP490_Ezstay"
      dockerfile: "PaymentAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/PaymentAPI.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "paymentapi:dev"
    ports: []
    volumes:
    - "/Users/quochien/.nuget/packages:/root/.nuget/packages"
    - "/Users/Kì 9/DeloymentPAYmentAPI/SEP490_Ezstay/PaymentAPI:/app:rw"
    - "/Users/Kì 9/DeloymentPAYmentAPI/SEP490_Ezstay:/src:rw"
    working_dir: "/app"
  utilitybillapi:
    build:
      context: "/Users/Kì 9/DeloymentPAYmentAPI/SEP490_Ezstay"
      dockerfile: "UtilityBillAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/UtilityBillAPI.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "utilitybillapi:dev"
    ports: []
    volumes:
    - "/Users/quochien/.nuget/packages:/root/.nuget/packages"
    - "/Users/Kì 9/DeloymentPAYmentAPI/SEP490_Ezstay/UtilityBillAPI:/app:rw"
    - "/Users/Kì 9/DeloymentPAYmentAPI/SEP490_Ezstay:/src:rw"
    working_dir: "/app"
